apiVersion: apps/v1
kind: Deployment
metadata:
  name: wargame-web
spec:
  selector:
    matchLabels:
      app: wargame-web
  template:
    metadata:
      labels:
        app: wargame-web
        node-type: webserver
    spec:
      nodeSelector:
        node-type: webserver
      initContainers:
      - name: check-image
        image: docker:cli
        command: 
        - /bin/sh
        - -c
        - |
          if docker pull localhost:5000/wargame-web:latest; then
            echo "localhost:5000/wargame-web:latest" > /image-name/image
          else
            echo "wargame-web:latest" > /image-name/image
          fi
        volumeMounts:
        - name: image-name
          mountPath: /image-name
      containers:
      - name: wargame-web
        image: localhost:5000/wargame-web:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "wargame-db-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: "LED_WG"
        - name: DB_USERNAME
          value: "wargame"
        - name: DB_PASSWORD
          value: "1234"
        volumeMounts:
        - name: image-name
          mountPath: /image-name
      volumes:
      - name: image-name
        emptyDir: {}
